### ISSUE TITLE
Rowspan attribute in table.xsl

### ISSUE THREAD

**Issue by vikbel** [ottoville/DOCX2HTML.XSL#3]
Please help me understand the following code in  table.xsl:

```
<xsl:choose>
<xsl:when test="$nextrestart='no'">
<xsl:attribute name="rowspan">
<xsl:value-of select="count(../following-sibling::w:tr/w:tc/w:tcPr/w:vMerge)+1"/>
</xsl:attribute>
</xsl:when>
<xsl:otherwise>
<xsl:for-each select="../following-sibling::w:tr[position() < $nextrestart]/*[position()=$curpos]/w:tcPr/w:vMerge">
<xsl:variable name="thisrowposition" select="count(./preceding-sibling::w:tr) + 1 - $rowposition"/>
<xsl:value-of select="$thisrowposition"/>
|
</xsl:for-each>
</xsl:otherwise>
</xsl:choose>
```

Why in the xsl:otherwise condition  "rowspan" attribute  is not defined?
For what is there symbol " | " ?
I watched Source code v0.6

**Comment by ottoville** [comment]
Hello Vikbel

That must been some junk left from debug. Otherwise section never get executed.
Once my github will co-operate with me, I will pull the newest version which has been cleaned from debug code.

**Comment by ottoville** [comment]
This code have now been cleaned, please check new table.xsl
https://github.com/ottoville/DOCX2HTML.XSL/blob/master/table.xsl

Let me know if you are facing any issues with rowspan

**Comment by vikbel** [comment]
Thanks
but in this code:

```
            <!-- Check if cell will span multiple cells -->
            <xsl:if test="w:tcPr/w:vmerge[@w:val='restart']">
                <xsl:attribute name="rowspan">
                    <xsl:value-of select="count(../following-sibling::w:tr/w:tc/w:tcPr/w:vmerge)+1"/>
                </xsl:attribute>
            </xsl:if>
```

сounting all "w:vmerge" to the end of the table. That is, the current rowspan attribute will have an incorrect value if the table contains a few merged cells. Only the last merge cells formed correctly. It is necessary to calculate "w:vmerge" to the nearest w:vmerge[@w:val='restart']

**Comment by ottoville** [comment]
Thank you for contributing.
This has now been fixed in latest version.
https://github.com/ottoville/DOCX2HTML.XSL/blob/master/table.xsl

**Comment by vikbel** [comment]
Great job! You helped me a lot. Thank you very much!
